SELECT DISTINCT
    'VALE' TIPO,
    CONVERT(VARCHAR,LANCAMENTO_OPERACAO.DATA_EFET,112) DATA, 
    REPLACE(LANCAMENTO_OPERACAO.VALOR_LANC_RS,'.','') VALOR,
    LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2,
    CASE WHEN PESSOA.INDICATIVO_PF_PJ = 'PF'
	     THEN PESSOA.PF_CPF
	     ELSE PESSOA.PJ_CGC
    END CPF_CNPJ,
    PESSOA.NOME_FANTASIA NOME,
    LANCAMENTO_OPERACAO.LANCAMENTO_OPERACAO_ID,
    FLAN.IDLAN,
    FXCX.IDXCX
FROM
    producao.cargosol.dbo.lancamento_operacao LANCAMENTO_OPERACAO WITH(NOLOCK)
JOIN producao.cargosol.dbo.PESSOA PESSOA WITH (NOLOCK) ON
	PESSOA.PESSOA_ID = ISNULL(LANCAMENTO_OPERACAO.COLABORADOR_ID,LANCAMENTO_OPERACAO.FORNECEDOR_ID)
JOIN LAYOUT_ARQUIVO WITH(NOLOCK) ON 
	LAYOUT_ARQUIVO.DATA_TRANSACAO = CONVERT(VARCHAR,LANCAMENTO_OPERACAO.DATA_EFET,112)
AND LAYOUT_ARQUIVO.VALOR_TRANSACAO = REPLACE(LANCAMENTO_OPERACAO.VALOR_LANC_RS,'.','')
AND CPF_FAVORECIDO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = CASE WHEN PESSOA.INDICATIVO_PF_PJ = 'PF'
															   THEN PESSOA.PF_CPF
															   ELSE PESSOA.PJ_CGC
														  END	
JOIN CORPORE_TEMP4..FLAN FLAN WITH (NOLOCK) ON
	FLAN.CAMPOALFAOP2 = LANCAMENTO_OPERACAO.LANCAMENTO_OPERACAO_ID
AND FLAN.CODCOLIGADA = 1
LEFT JOIN CORPORE_TEMP4..FLANBAIXA FLANBAIXA WITH(NOLOCK) ON
    FLANBAIXA.IDLAN = FLAN.IDLAN
AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA		
LEFT JOIN CORPORE_TEMP4..FXCX FXCX WITH(NOLOCK) ON
    FXCX.IDXCX = FLANBAIXA.IDXCX
AND FXCX.CODCOLIGADA = FLANBAIXA.CODCOLIGADA									  
WHERE
    LAYOUT_ARQUIVO.DATA_TRANSACAO = 20140708
AND LAYOUT_ARQUIVO.TIPO_TRANSACAO <> 1		
		
UNION ALL

SELECT
    'PEDAGIO' TIPO, 
    DATA_TRANSACAO DATA, 
    VALOR_TRANSACAO VALOR, 
    NUM_AUTORIZACAO_2,
    CPF_CNPJ_CONTRATADO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS, 
    NOME_CONTRATADO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS, 
    NULL LANCAMENTO_OPERACAO_ID,
    NULL IDLAN,
    NULL IDXCX
FROM
    LAYOUT_ARQUIVO WITH(NOLOCK)
WHERE
    DATA_TRANSACAO = 20140708	
AND TIPO_TRANSACAO = 1
ORDER BY
    TIPO DESC


/*
SELECT
    'VALE' TIPO,
    CONVERT(VARCHAR,LANCAMENTO_OPERACAO.DATA_EFET,112) DATA, 
    REPLACE(LANCAMENTO_OPERACAO.VALOR_LANC_RS,'.','') VALOR,
    LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2,
    CASE WHEN PESSOA.INDICATIVO_PF_PJ = 'PF'
	     THEN PESSOA.PF_CPF
	     ELSE PESSOA.PJ_CGC
    END CPF_CNPJ,
    PESSOA.NOME_FANTASIA NOME,
    LANCAMENTO_OPERACAO.LANCAMENTO_OPERACAO_ID,
    FLAN.IDLAN,
    FXCX.IDXCX
FROM
    CORPORE_TEMP4..FXCX FXCX
JOIN CORPORE_TEMP4..FLANBAIXA FLANBAIXA WITH(NOLOCK) ON
    FLANBAIXA.IDXCX = FXCX.IDXCX
AND FLANBAIXA.CODCOLIGADA = FXCX.CODCOLIGADA
JOIN CORPORE_TEMP4..FLAN FLAN WITH(NOLOCK) ON
    FLAN.IDLAN = FLANBAIXA.IDLAN
AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA	
JOIN CARGOSOL..LANCAMENTO_OPERACAO LANCAMENTO_OPERACAO WITH(NOLOCK) ON
    LANCAMENTO_OPERACAO.LANCAMENTO_OPERACAO_ID = FLAN.CAMPOALFAOP2    
JOIN CARGOSOL..PESSOA PESSOA WITH (NOLOCK) ON
	PESSOA.PESSOA_ID = ISNULL(LANCAMENTO_OPERACAO.COLABORADOR_ID,LANCAMENTO_OPERACAO.FORNECEDOR_ID)
JOIN LAYOUT_ARQUIVO WITH(NOLOCK) ON 
	LAYOUT_ARQUIVO.DATA_TRANSACAO = CONVERT(VARCHAR,LANCAMENTO_OPERACAO.DATA_EFET,112)
AND LAYOUT_ARQUIVO.VALOR_TRANSACAO = REPLACE(LANCAMENTO_OPERACAO.VALOR_LANC_RS,'.','')
AND CPF_FAVORECIDO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = CASE WHEN PESSOA.INDICATIVO_PF_PJ = 'PF'
															   THEN PESSOA.PF_CPF
															   ELSE PESSOA.PJ_CGC
														  END							  
WHERE
    LAYOUT_ARQUIVO.DATA_TRANSACAO = 20140612
AND LAYOUT_ARQUIVO.TIPO_TRANSACAO <> 1	
AND FXCX.CODCOLIGADA = 1


UPDATE FXCX
SET FXCX.NUMERODOCUMENTO = 
--select
    CASE WHEN LEN(LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2) <= 6
		    THEN RTRIM(CAST(LAYOUT_ARQUIVO.DOCUMENTO_EXTRATO AS VARCHAR)+'00'+CAST(LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2 AS VARCHAR))
		    ELSE CASE WHEN LEN(LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2) = 7
					    THEN RTRIM(CAST(LAYOUT_ARQUIVO.DOCUMENTO_EXTRATO AS VARCHAR)+'0'+CAST(LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2 AS VARCHAR))
					    ELSE RTRIM(CAST(LAYOUT_ARQUIVO.DOCUMENTO_EXTRATO AS VARCHAR)+CAST(LAYOUT_ARQUIVO.NUM_AUTORIZACAO_2 AS VARCHAR))
			     END
END
FROM
    CORPORE_TEMP4..FXCX FXCX
JOIN CORPORE_TEMP4..FLANBAIXA FLANBAIXA WITH(NOLOCK) ON
    FLANBAIXA.IDXCX = FXCX.IDXCX
AND FLANBAIXA.CODCOLIGADA = FXCX.CODCOLIGADA
JOIN CORPORE_TEMP4..FLAN FLAN WITH(NOLOCK) ON
    FLAN.IDLAN = FLANBAIXA.IDLAN
AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA	
JOIN PRODUCAO.CARGOSOL.DBO.LANCAMENTO_OPERACAO LANCAMENTO_OPERACAO WITH(NOLOCK) ON
    LANCAMENTO_OPERACAO.LANCAMENTO_OPERACAO_ID = FLAN.CAMPOALFAOP2    
JOIN PRODUCAO.CARGOSOL.DBO.PESSOA PESSOA WITH (NOLOCK) ON
	PESSOA.PESSOA_ID = ISNULL(LANCAMENTO_OPERACAO.COLABORADOR_ID,LANCAMENTO_OPERACAO.FORNECEDOR_ID)
JOIN LAYOUT_ARQUIVO WITH(NOLOCK) ON 
	LAYOUT_ARQUIVO.DATA_TRANSACAO = CONVERT(VARCHAR,LANCAMENTO_OPERACAO.DATA_EFET,112)
AND LAYOUT_ARQUIVO.VALOR_TRANSACAO = REPLACE(LANCAMENTO_OPERACAO.VALOR_LANC_RS,'.','')
AND CPF_FAVORECIDO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = CASE WHEN PESSOA.INDICATIVO_PF_PJ = 'PF'
															   THEN PESSOA.PF_CPF
															   ELSE PESSOA.PJ_CGC
														  END							  
WHERE
    LAYOUT_ARQUIVO.TIPO_TRANSACAO <> 1	
AND FXCX.CODCOLIGADA = 1
AND FXCX.IDXCX IN (408357,408356)

/*
select * from CORPORE_TEMP4..fxcx where FXCX.CODCOLIGADA = 1
and FXCX.idxcx in (408357,408356)

select * from CORPORE_TEMP4..flanbaixa where idxcx in (408357,408356)


*/

--COMMIT
--ROLLBACK
*/


/*

SELECT * FROM LAYOUT_ARQUIVO

SELECT IDLAN,* FROM CORPORE_TEMP4..FXCX WHERE IDXCX = 404142
SELECT * FROM CORPORE_TEMP4..FLANBAIXA WHERE IDLAN = 8078801

*/
